# Generated by Django 4.2.5 on 2023-09-20 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 17, 19, 58, 820948)),
        ),
    ]
