# Generated by Django 4.2.5 on 2023-09-25 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 17, 54, 31, 922714)),
        ),
    ]
