# Generated by Django 4.2.5 on 2023-09-27 19:42

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_counteudo_post_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 19, 42, 40, 533956, tzinfo=datetime.timezone.utc)),
        ),
    ]
